services:
  postgres:
    image: postgres
    container_name: postgres_sixt
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    networks:
      - default

  redis:
    image: redis:latest
    container_name: redis_sixt
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - default
    command: redis-server --appendonly yes
    volumes:
      - redis:/data

#  app:
#    container_name: sixt
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: password
#      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
#      SPRING_REDIS_HOST: redis
#      SPRING_REDIS_PORT: 6379
#    depends_on:
#      - postgres
#      - redis
#    networks:
#      - default

networks:
  default:
    name: sixt

volumes:
  postgres:
  redis: